services:

  mariadb:

    build:
      context: ./requirements/mariadb 

    container_name: mariadb

    env_file:
      - .env

    volumes:
      - mariadb_data:/var/lib/mysql

    networks:
      - inception 

    restart: on-failure


  wordpress:

    build:
      context: ./requirements/wordpress

    container_name: wordpress

    env_file:
      - .env

    volumes: 
      - wordpress_data:/var/www/html 

    networks: 
      - inception 

    depends_on:
      - mariadb 

    restart: on-failure


  nginx:

    build:
      context: ./requirements/nginx

    container_name: nginx

    ports:
      - "443:443"

    volumes:
      - wordpress_data:/var/www/html

    networks:
      - inception 

    depends_on:
      - wordpress 

    restart: on-failure 


volumes: 

  mariadb_data: 
    driver: local
    driver_opts: 
      type: none 
      device: /home/omaezzem/data/mariadb 
      o: bind


  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/omaezzem/data/wordpress
      o: bind


networks:

  inception:
    driver: bridge