server {
    listen 443 ssl; #ssl = Nginx khaso yst3mel TLS bach y9bel HTTPS connections.
    server_name omaezzem.42.fr; #had server block howa li khas yhandleha

    ssl_certificate /etc/nginx/ssl/inception.crt; #Hna Nginx kay3ti certificate dyalo l browser during TLS handshake.
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    ssl_protocols TLSv1.2 TLSv1.3;

    root /var/www/html; # hada root file ya3ni ayi file ki9eleb 3lih nginx ghdi il9ah hna 
    index index.php;

    location / {
        try_files $uri $uri/ =404; #ki9eleb wach hadak file kin ola dak dir kin maknch kireje3 not found 
    }

    location ~ \.php$ {
        include fastcgi_params; #kiloadi bzzf diyal parames likhassin bach yseft request l fastcgi
        fastcgi_pass wordpress:9000; #port li php-fpm kiilistni 3lih 
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name; #matching like that /var/www/html/index.php 
    }
}

